config/routes.rb
Surveytesting::Application.routes.draw do

  resources :answers

  devise_for :users
  root 'home#index'
  get "home/index"

  resources :results

  resources :surveys do
    collection do 
      get "my_surveys"
      post "make_survey_save"
      get "check_survey_email"
    end
    member do
      get "add_answer"
      get "make_survey"
      get "result"
    end
  end

  resources :categories


end

app/models/result.rb
class Result < ActiveRecord::Base

  belongs_to :survey
  belongs_to :answer

  

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @result }
      else
        format.html { render action: 'new' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:survey_id, :answer_id, :another_content, :answer_email)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.haml
= simple_form_for(@result) do |f|
  = f.error_notification

  .form-inputs
    = f.input :survey_id
    = f.input :answer_id
    = f.input :another_content
    = f.input :answer_email

  .form-actions
    = f.button :submit

app/views/results/edit.html.haml
%h1 Editing result

= render 'form'

= link_to 'Show', @result
\|
= link_to 'Back', results_path

app/views/results/index.html.haml
%h1 Listing results

%table
  %tr
    %th Survey
    %th Answer
    %th Another content
    %th Answer email
    %th
    %th
    %th

  - @results.each do |result|
    %tr
      %td= result.survey_id
      %td= result.answer_id
      %td= result.another_content
      %td= result.answer_email
      %td= link_to 'Show', result
      %td= link_to 'Edit', edit_result_path(result)
      %td= link_to 'Destroy', result, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Result', new_result_path

app/views/results/new.html.haml
%h1 New result

= render 'form'

= link_to 'Back', results_path

app/views/results/show.html.haml
%p#notice= notice

%p
  %b Survey:
  = @result.survey_id
%p
  %b Answer:
  = @result.answer_id
%p
  %b Another content:
  = @result.another_content
%p
  %b Answer email:
  = @result.answer_email

= link_to 'Edit', edit_result_path(@result)
\|
= link_to 'Back', results_path