config/routes.rb
Surveytesting::Application.routes.draw do

  resources :answers

  devise_for :users
  root 'home#index'
  get "home/index"

  resources :results

  resources :surveys do
    collection do 
      get "my_surveys"
      post "make_survey_save"
      get "check_survey_email"
    end
    member do
      get "add_answer"
      get "make_survey"
      get "result"
    end
  end

  resources :categories


end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :survey
  has_many :results

  validates :survey_id, :content,  :presence => true
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:survey_id, :content)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
= simple_form_for(@answer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :survey_id
    = f.input :content

  .form-actions
    = f.button :submit

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Survey
    %th Content
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= answer.survey_id
      %td= answer.content
      %td= link_to 'Show', answer
      %td= link_to 'Edit', edit_answer_path(answer)
      %td= link_to 'Destroy', answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Survey:
  = @answer.survey_id
%p
  %b Content:
  = @answer.content

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path