config/routes.rb
Surveytesting::Application.routes.draw do

  resources :answers

  devise_for :users
  root 'home#index'
  get "home/index"

  resources :results

  resources :surveys do
    collection do 
      get "my_surveys"
      post "make_survey_save"
      get "check_survey_email"
    end
    member do
      get "add_answer"
      get "make_survey"
      get "result"
    end
  end

  resources :categories


end

app/models/survey.rb
class Survey < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  has_many :answers, :order => 'created_at', :dependent => :destroy
  has_many :results

  accepts_nested_attributes_for :answers, :allow_destroy => true
  # accepts_nested_attributes_for :answers, :reject_if => :all_blank , :allow_destroy => true

  ANSWER_TYPE = {
    :single_choice    => 1,
    :multiple_choice  => 2,
    # :single_box       => 3,
    # :multiple_box     => 4
  }

  def is_owner
    user.id == self.user_id
  end

  def is_single_choice
    self.answer_type == ANSWER_TYPE[:single_choice]
  end

  def is_multiple_choice
    self.answer_type == ANSWER_TYPE[:multiple_choice]
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :add_answer, :make_survey,:result]
  before_filter :authenticate_user!, :except => [:destroy, :make_survey, :make_survey_save]

  # GET /surveys
  # GET /surveys.json
  def index
    if current_user.is_admin
      @surveys = Survey.all
    else
      redirect_to my_surveys_surveys_url
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @categories = Category.all
  end

  def add_answer
    if @survey.answers && @survey.answers.count > 0
      @answers = @survey.answers
    else
      @answers = @survey.answers.build
    end
  end

  # GET /surveys/1/edit
  def edit
    @categories = Category.all
    # @answers = @survey.answers.build
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    # @survey.answers.build(params[:answers_attributes])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to add_answer_survey_path(@survey) }
        format.json { render action: 'show', status: :created, location: @survey }
      else
        format.html { render action: 'new' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        if params[:another_answer]
          Answer.create(:survey_id => @survey.id,:content => "Other", :is_other => true)
        end
        if params[:add_answers_action] && params[:add_answers_action] == 'add_answers'
          format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        else
          format.html { redirect_to add_answer_survey_path(@survey) }
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end

  def my_surveys
    @surveys = current_user.surveys

    # @q = current_user.surveys.order("created_at DESC").search(params[:q])
    # @surveys = @q.result
  end

  def make_survey
  end

  def make_survey_save
    survey_id       = params[:survey_id]
    answer_choice   = params[:user_answer_choice]
    answer_email    = params[:answer_email]
    other_answer    = params[:other_answer]
    other_answer_id = params[:other_answer_id]
    results         = Array.new

    resutl_num  = Result.where(:survey_id => survey_id, :answer_email => answer_email).count
    if resutl_num > 0 
      survey = Survey.find(survey_id)
      redirect_to make_survey_survey_path(survey), notice: 'This email have pushed survey. Please push survey with another email.'
    else
      arr_answer = answer_choice.split(",")
      arr_answer.each do |answer_id|
        results << {
                      :survey_id    => survey_id,
                      :answer_id    => answer_id,
                      :answer_email => answer_email
                    }
      end
      if other_answer.strip.length > 0
        results << {
                      :survey_id    => survey_id,
                      :answer_id    => other_answer_id,
                      :answer_email => answer_email,
                      :another_content => other_answer
                    }
      end
      Result.create(results)
      redirect_to root_path, notice: 'Survey was successfully created.' 
    end
  end

  def check_survey_email
    survey_id   = params[:survey_id]
    user_email  = params[:user_email]
    existing    = false
    resutl_num  = Result.where(:survey_id => survey_id, :answer_email => user_email).count
    if resutl_num > 0
      existing = true
    end
    render :json => {:success => true, :data => existing}
  end

  def result
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:question, :user_id,:category_id, :answer_type, answers_attributes: [:id, :survey_id, :content] )
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper

end

app/views/surveys/_chart_script.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    $("#view_chart").addClass( "hidden" );
    
    var result = document.getElementById('arr_answer_result').value;
    if(result.length > 0){
      var arr_result = result.split(",");    
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Number');
      data.addColumn('number', 'Answer');
      for(var i=0; i < arr_result.length; i++){
        if(arr_result[i].length > 0) {
          arr = arr_result[i].split("_");
          var x = arr[0];
          var y = parseInt(arr[1]);
          data.addRows([[x,y]]);
        }
      }

      var options = {
        // title: 'Company Performance',
        hAxis: {title: 'Result', titleTextStyle: {color: 'red'}}
      };

      var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
      chart.draw(data, options);
      
    }
  }
</script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>

app/views/surveys/_form.html.haml
- if @categories && @categories.size > 0
  = simple_form_for(@survey) do |f|
    = f.error_notification

    .form-inputs
      = f.hidden_field :user_id, :value => current_user.id
      = f.input :question
      / = f.input :answer_type
      .field
        = f.label :category
        = f.collection_select :category_id, @categories, :id, :name
      .field
        = f.label :answer_type
        = f.select :answer_type, Survey::ANSWER_TYPE.to_a

    .form-actions
      = f.button :submit
- else
  .center
    You must create category first

app/views/surveys/_list_surveys.html.haml
%table.table-condensed
  %tr
    %th.num No
    %th Question
    %th.date Created
    %th.num Total
    %th.link Link
  - if surveys && surveys.size > 0
    - surveys.each_with_index do |survey,i|
      %tr
        %td.center= i + 1
        %td= link_to survey.question, survey_path(survey)
        %td= survey.created_at.strftime(I18n.t('time.format'))
        %td
          = survey.answers.count if survey.answers
        %td.center
          = link_to I18n.t('common.result'), result_survey_path(survey)
          |
          = link_to I18n.t('common.edit'), edit_survey_path(survey)
          - if current_user.is_admin or survey.is_owner
            |
            = link_to I18n.t('common.delete'), survey_path(survey), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/surveys/_search_form.html.haml
.search_box
  = search_form_for @q do |f|
    .input.seach-query
      = f.text_field :question_cont, :class => "search_query_txt search-query survey", :placeholder => I18n.t('content.club_info.title')
      %button.search_btn.btn{:type => "submit"}= I18n.t('content.survey.question')

app/views/surveys/_survey_content.html.haml
.text.font20.bold= @survey.question
- if @survey.answers
  .answer_fields_box
    = hidden_field_tag "survey_id", @survey.id, :id => "survey_id"
    = hidden_field_tag "answer_type", @survey.answer_type, :id => "answer_type"
    = hidden_field_tag "user_answer_choice", '', :id => "user_answer_choice"
    - survey.answers.each do |answer|
      - unless answer.is_other
        .answer_fields.clearfix
          - if survey.is_single_choice
            .single_choice
              %input{:type => "radio", :name => "answer_choice", :value => answer.id, :class => "answer_single_choice"}
          - else
            .multiple_choice
              %input{:type => "checkbox", :value => answer.id, :class => "answer_multiple_choice", :name => "answer_choice"}
          %span= answer.content
      - else
        .answer_fields
          = hidden_field_tag "other_answer_id", answer.id, :id => "other_answer_id"
          %span= answer.content
          %input{:type => "text", :name => "other_answer", :class => "other_answer", :id => "other_answer"}

app/views/surveys/_survey_show.html.haml
.text.font20.bold= @survey.question
- if @survey.answers
  .answer_fields_box
    - index = 0 
    - survey.answers.each_with_index do |answer,i|
      - unless answer.is_other
        .answer_fields.clearfix
          %span= "#{i + 1 }."
          %b= answer.content
          - index = i + 1 
      - else
        .answer_fields
          %span= "#{index + 1}."
          %b= answer.content

app/views/surveys/add_answer.html.haml
.text.font20.bold= @survey.question
.add_answer_form.clearfix
  .text.bold Add answer option 
  = simple_nested_form_for @survey do |f|
    = hidden_field_tag "add_answers_action", "add_answers"
    .answer_box
      = f.fields_for :answers do |f|
        .answer_fields
          = f.input :content, :label => "Answer", :class => "answer_content"
          = f.link_to_remove "remove", :class => "btn btn_remove_content"
    = f.link_to_add(:answers, :class => "add_answers", :href => '#') do
      .btn Add
    .fields
      = f.label :another
      %input{:type => "checkbox",:name => "another_answer", :class => "another_checkbox"}
    .action_fields
      = f.button :submit, :value => "Save"

app/views/surveys/edit.html.haml
.text.font20.bold Editing survey

= render 'form'

= link_to 'Show', @survey
\|
= link_to 'Back', surveys_path

app/views/surveys/index.html.haml
.surveys
  .text.font14.bold Listing surveys

  .list_surveys= render 'list_surveys', :surveys => @surveys

app/views/surveys/make_survey.html.haml
= simple_form_for(:survey, :url => make_survey_save_surveys_path, :html => {:method => "post"}) do |f|
  = render 'survey_content', :survey => @survey
  .answer_email_fields
    %span Your email
    %input{:type => "text", :name => "answer_email", :class => "answer_email", :id => "answer_email"}
  .action_form
    = f.button :submit, :id => "make_user_survey"

app/views/surveys/my_surveys.html.haml
.my_surveys
  .text.font14.bold=I18n.t('content.survey.my_survey')

  .list_surveys= render 'list_surveys', :surveys => @surveys
  = link_to I18n.t('content.survey.create'), new_survey_path, :class => "btn"

app/views/surveys/new.html.haml
.text.font20.bold New survey

= render 'form'

= link_to 'Back', surveys_path

app/views/surveys/result.html.haml
.text.font20.bold= @survey.question
%br
.number_table
  %ul
    - arr_answer = ""
    -@survey.answers.each_with_index do |answer,i|
      - rs_count = answer.results.count
      - arr_answer = "Answer #{i + 1}_#{rs_count}," + arr_answer
      %li 
        %p
          %span= "Answer #{i + 1}: "
          = answer.content
          .text.font20
            %span= "=>" 
            %span.red= rs_count
= hidden_field_tag "arr_answer_result", arr_answer, :id => "arr_answer_result"
= link_to "View chart", "#", :id => "view_chart", :class => "btn btn-primary"
.chart_data
  = render 'chart_script'

app/views/surveys/show.html.haml
%p
  %span Category:
  %b= @survey.category.name if @survey.category
= render 'survey_show', :survey => @survey
%br
%p
  %b Survey link:
  = make_survey_survey_url(@survey)

= link_to 'Edit', edit_survey_path(@survey)
\|
= link_to 'Back', surveys_path