config/routes.rb
Surveytesting::Application.routes.draw do

  resources :answers

  devise_for :users
  root 'home#index'
  get "home/index"

  resources :results

  resources :surveys do
    collection do 
      get "my_surveys"
      post "make_survey_save"
      get "check_survey_email"
    end
    member do
      get "add_answer"
      get "make_survey"
      get "result"
    end
  end

  resources :categories


end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :surveys

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
.text.font20.bold Listing categories
.list_data
  %table.table-condensed
    %tr
      %th.id #No
      %th Name
      %th Description
      %th.link Link
    - if @categories && @categories.size > 0
      - @categories.each_with_index do |category,i|
        %tr
          %td= i + 1 
          %td= category.name
          %td= category.description
          %td.center
            = link_to 'Show', category
            |
            = link_to 'Edit', edit_category_path(category)
            |
            = link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }
  = link_to 'New Category', new_category_path, :class => "btn"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p
  %b Name:
  = @category.name
%p
  %b Description:
  = @category.description

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path